// frontend/src/component/dashboard/index.tsx
import { Link } from 'react-router-dom';
import { useState, useEffect } from 'react'
import { BASEURL } from '../../config'
import { useNavigate } from 'react-router-dom'
import { AlertModal } from '../modal'
import {openModalWithVariantAndMessage} from '../../utility'

export const Dashboard = () => {
    const [listData, setlistData] = useState([])
    const [count, setCount] = useState(0)
    const [modalVariant, setModalVariant] = useState("success")
    const [modalMessage, setModalMessage] = useState("")
    const [modal, showModal] = useState(false)

    const fixedModalParameters = [showModal, setModalMessage, setModalVariant]
    const navigate = useNavigate();
  

    const getListData = () => {
        fetch(`${BASEURL}`).then(res => res.json()).then((res) => {
            const { count, data } = res
            setCount(Number(count))
            setlistData(data)
        })
    }



    const deleteTask = (id: Number) => {
        fetch(`${BASEURL}/${id}`, { method: 'DELETE' }).then(res => res.json()).then((res) => {
            const { code, message } = res
            if (code === 200) {
                openModalWithVariantAndMessage(message, "success", fixedModalParameters)
                getListData()
            }
        }).catch(() => {
            // openModalWithVariantAndMessage("Sorry something went wrong!", "danger", fixedModalParameters)
        })
    }

    useEffect(() => {
        getListData()
    }, [])

    const navigateToListItemDetails = (id: Number) => {
        navigate(`/task/${id}`)
    }

    return (
        <>
            <AlertModal variant={modalVariant} message={modalMessage} onhide={showModal} showmodal={modal} />
            <div>
                <div className="d-flex justify-content-center my-3">
                    <strong className="fs-3">Dashboard</strong>
                </div>

                <div className="d-flex justify-content-end mb-3 me-3 ">
                    <Link to='/addtodo'>Add New Task</Link>
                </div>

                {
                    listData.map((item: any) => {
                        return (
                            <div className='m-3 border p-2  d-flex justify-content-between' key={item.id}>
                                <div onClick={() => navigateToListItemDetails(item.id)} className='text-break hover'>
                                    {item.title}
                                </div>

                                <div>
                                    <i onClick={() => deleteTask(item.id)} className='bi bi-trash3 hover'></i>
                                </div>
                            </div>
                        )
                    })
                }






                {
                    count === 0 && <div className="d-flex justify-content-center mt-5 lead">
                        You have not added any task. Please add task
                    </div>
                }

            </div>
        </>
    );
}

// frontend/src/app/components/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { ToDoListService } from '../../services/tododata'
import { task } from '../../interfaces/index'
import { PageEvent } from '@angular/material/paginator';
import { Router } from '@angular/router';

import {
  MatSnackBar,
  MatSnackBarHorizontalPosition,
  MatSnackBarVerticalPosition,
} from '@angular/material/snack-bar';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  limit: number = 10
  offset: number = 0
  pageSizeOptions: number[] = [5, 10, 25, 100];
  horizontalPosition: MatSnackBarHorizontalPosition = 'end';
  verticalPosition: MatSnackBarVerticalPosition = 'top';
  constructor(private todolistservice: ToDoListService, private _snackBar: MatSnackBar, private router: Router) { }

  listData: task[] = []
  length = 10
  ngOnInit(): void {
    this.getListData()
  }

  navigateToATask(id?:Number) {
    this.router.navigate([`/task/${id}`])
  }

  getListData() {
    this.todolistservice.getTasksList(this.limit, this.offset).subscribe((res) => {
      const { data, code, count } = res
      if (code == 200) {
        this.listData = data
        this.length = count
      }
    }, (error) => {
      console.log(error)
    })
  }

  deleteTask(id?: Number) {
    this.todolistservice.deleteTask(id).subscribe((res) => {
      const {code, message} = res
      if (code == 200) {
        this.openSnackBar(message, "bg-success")
        this.getListData()
      }
    }, (err) => {
      this.openSnackBar("Sorry something went wrong", "bg-danger")
    })
  }

  handlePageEvent(event: PageEvent) {
    const { pageSize, pageIndex } = event
    this.limit = pageSize
    this.offset = pageIndex
    this.getListData()
  }

  openSnackBar(message: string, matBackgroundClass: string) {
    this._snackBar.open(message, '', {
      horizontalPosition: this.horizontalPosition,
      verticalPosition: this.verticalPosition,
      duration: 2000,
      panelClass: [matBackgroundClass]
    });
  }
}

<div>
    <div class="d-flex justify-content-center my-3">
        <strong class="fs-3">Dashboard</strong>
    </div>

    <div class="d-flex justify-content-end mb-3 me-3 ">
        <a class="" [routerLink]="['/addtodo']">
            Add New Task
        </a>
    </div>
    <div>
        <div class="m-3 border p-2  d-flex justify-content-between" *ngFor="let listitem of listData">
            <div (click)="navigateToATask(listitem.id)" class="text-break hover">
                <strong>{{listitem.title}}</strong>
            </div>

            <div>
                <i (click)="deleteTask(listitem.id)" class="bi bi-trash3 hover"></i>
            </div>
        </div>
    </div>

    <div *ngIf="listData.length > 0" class="d-flex justify-content-end mt-5">
        <mat-paginator (page)="handlePageEvent($event)" [length]="length" [pageSize]="limit"
            [pageSizeOptions]="pageSizeOptions" [pageIndex]="offset"
            aria-label="Select page">
        </mat-paginator>
    </div>

    <div *ngIf="listData.length == 0" class="d-flex justify-content-center mt-5 lead">
        You have not added any task. Please add task
    </div>
</div>
